public class IntegerFrame extends javax.swing.JFrame {

    /**
     * Creates new form Integer
     */
    public IntegerFrame() {
        initComponents();
        jTable1.setValueAt("Значение", 0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        inputField = new javax.swing.JTextField();
        translateButton = new javax.swing.JButton();
        RightShiftButton = new javax.swing.JButton();
        leftShiftButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        outputField = new javax.swing.JTextField();
        reverseTranslateButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Вес бита", "32768", "16384", "8192", "4096", "2048", "1024", "512", "256"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "128", "64", "32", "16", "8", "4", "2", "1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        translateButton.setText("Перевод из 10 СС");
        translateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateButtonActionPerformed(evt);
            }
        });

        RightShiftButton.setText(">>");
        RightShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightShiftButtonActionPerformed(evt);
            }
        });

        leftShiftButton.setText("<<");
        leftShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftShiftButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Знак");

        reverseTranslateButton.setText("Обратный перевод");
        reverseTranslateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseTranslateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(translateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(inputField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(leftShiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(RightShiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(764, 764, 764))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(reverseTranslateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(translateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftShiftButton)
                    .addComponent(RightShiftButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reverseTranslateButton))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void translateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateButtonActionPerformed
        int num = Integer.parseInt(inputField.getText());
        int invert = 0;
        int incr = 0;
       
        if (num < 0) {
            jTable1.setValueAt(1, 0,1);
            num = -num;
            invert = 1;
        }
        else {
            jTable1.setValueAt(0, 0, 1);
        }
       
        for (int i = 7; i >= 0; i--) {
            jTable4.setValueAt(Math.abs(num % 2 - invert), 0, i);
            if (i == 7 && invert == 1) {
                if ((int)jTable4.getValueAt(0, i) == 0) {
                    jTable4.setValueAt(1, 0, i);
                }
                else {
                    jTable4.setValueAt(0, 0, i);
                    incr = 1;
                }
            }
            else {
                if (incr == 1) {
                if ((int)jTable4.getValueAt(0, i) == 0) {
                    jTable4.setValueAt(1, 0, i);
                    incr = 0;
                }
                else {
                    jTable4.setValueAt(0, 0, i);
                }
            }
            }
            num /= 2;
        }
        for (int i = 8; i >= 2; i--) {
            jTable1.setValueAt(Math.abs(num % 2 - invert), 0, i);
            if (incr == 1) {
                if ((int)jTable1.getValueAt(0, i) == 0) {
                    jTable1.setValueAt(1, 0, i);
                    incr = 0;
                }
                else {
                    jTable1.setValueAt(0, 0, i);
                }
            }
            num /= 2;
        }
    }//GEN-LAST:event_translateButtonActionPerformed

    private void leftShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftShiftButtonActionPerformed
        jTable4.setValueAt(0, 0, 7);
        int prev = (int)jTable4.getValueAt(0, 7);
        int cur;

        for (int i = 6; i >= 0; i--) {
            cur = (int)jTable4.getValueAt(0, i);
            jTable4.setValueAt(prev, 0, i);
            prev = cur;
        }
        
        for (int i = 8; i >= 1; i--) {
            cur = (int)jTable1.getValueAt(0, i);
            jTable1.setValueAt(prev, 0, i);
            prev = cur;
        }
    }//GEN-LAST:event_leftShiftButtonActionPerformed

    private void RightShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightShiftButtonActionPerformed
        jTable1.setValueAt(0, 0, 1);
        int prev = (int)jTable1.getValueAt(0, 1);
        int cur;

        for (int i = 2; i < 9; i++) {
            cur = (int)jTable1.getValueAt(0, i);
            jTable1.setValueAt(prev, 0, i);
            prev = cur;
        }
        
        for (int i = 0; i < 8; i++) {
            cur = (int)jTable4.getValueAt(0, i);
            jTable4.setValueAt(prev, 0, i);
            prev = cur;
        }
    }//GEN-LAST:event_RightShiftButtonActionPerformed

    private void reverseTranslateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseTranslateButtonActionPerformed
        int num = 0;
        int cur;
        
        for (int i = 7; i >= 0; i--) {
            cur = (int)jTable4.getValueAt(0, i);
            num += cur * Math.pow(2, Math.abs(i - 7));
        }
        
        for (int i = 8; i >= 2; i--) {
            cur = (int)jTable1.getValueAt(0, i);
            num += cur * Math.pow(2, Math.abs(i - 8) + 8);
        }
        
        if ((int)jTable1.getValueAt(0, 1) == 1) {
            num = -num;
        }
        
        outputField.setText(inputField.getText());
    }//GEN-LAST:event_reverseTranslateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RightShiftButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton leftShiftButton;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton reverseTranslateButton;
    private javax.swing.JButton translateButton;
    // End of variables declaration//GEN-END:variables
}
